[package]
name = "mpc-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
sha3 = "0.10"
rsa = "0.9.7"
serde = { version = "1.0.216", features = ["derive"] }
bincode = "1.3.3"
