[package]
name = "mpc-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
rand = "0.8.5"
rsa = "0.9.7"
rug = "1.26"
serde = { version = "1.0.216", features = ["derive"] }
sha3 = "0.10"
